export const INITIAL_WORDS = [
  "MUCHO GUSTO",
  "SOL DE ORO",
  "CASA FELIZ",
  "BUEN AMIGO",
  "LUZ DEL DIA",
  "MAR Y CIELO",
  "FLOR BONITA",
  "NOCHE OSCURA",
  "VIDA FELIZ",
  "RIO TRANQUILO",
  "CAMPO VERDE",
  "NUBE BLANCA",
  "FUEGO ARDIENTE",
  "SOL BRILLANTE",
  "AIRE FRESCO",
  "MUNDO NUEVO",
  "VERANO CALIDO",
  "LUNA LLENA",
  "BOSQUE VERDE",
  "MAR EN CALMA"
];

